name: deploy

on:
  push:
    branches:
      - main
    paths-ignore:
      - "README.md"
      - ".github/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: "1.19"

      - name: go get aws lambda library
        run: go get github.com/aws/aws-lambda-go/lambda

      - name: go build
        run: GOOS=linux go build -o datsukan-blog-publish-tweet main.go

      - name: create zip
        run: zip datsukan-blog-publish-tweet.zip datsukan-blog-publish-tweet

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: upload datsukan-blog-publish-tweet.zip to s3
        run: aws s3 cp datsukan-blog-publish-tweet.zip s3://datsukan-blog-publish-lambda-deploy

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: update Lambda function
        run: |
          aws lambda update-function-code --function-name datsukan-blog-publish-tweet --s3-bucket datsukan-blog-publish-lambda-deploy --s3-key datsukan-blog-publish-tweet.zip\
          | jq '.FunctionName, .LastUpdateStatus'
